all_products_links: '//*[@class="product_img_link pro_img_hover_scale product-list-category-img"]/@href'
product_name_route: "//div/h1[@class='product_main_name']"
number_of_products: '//*[@id="nb_item_bottom"]/@value'
product_image_link_route: "//div/span/img[@id='bigpic']/@src"
product_weight_price_for_loop: '//fieldset//ul/li'
url: 'https://www.petsonic.com/farmacia-para-gatos/'
product_weight_route: "//div/ul/li/label/span[@class='radio_label']"
product_price_route: "//div/ul/li/label/span[@class='price_comb']"
file_name: 'data.csv'